// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzafyWeb.Data;

#nullable disable

namespace PizzafyWeb.Migrations
{
    [DbContext(typeof(PizzafyDbContext))]
    partial class PizzafyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0");

            // ...existing model... (keep as generated previously)
            // Only update the OrderItem mapping block name and columns
        }
    }
}
